### ISSUE TITLE
upload png but return jpg

### ISSUE THREAD

**Issue by zeteticl** [0wx/imgbox#1]
Hello, i try to upload png by
const response = await imgbox("https://www.adobe.com/hk_en/creativecloud/file-types/image/raster/media_19531d2c5f311776c67e44b76083db13309004956.png");

but return 
https://imgbox.com/w1UlxNyW 

how can i fix it?

**Comment by 0wx** [comment]
@zeteticl based on the code you provide, the `response` should have this properties:
```js
{
  ok: true,
  gallery_edit: 'https://imgbox.com/gallery/edit/xxx/xx2RGGW23AFNO6A',
  files: [
    {
      id: 'ZeNbMgP7',
      slug: 'ZeNbMgP7',
      name: 'b7910796-6aed-406d-be8b-4307a4d74613.jpg',
      name_html_escaped: 'b7910796-6aed-406d-be8b-4307a4d74613.jpg',
      created_at: '2024-09-26T07:33:53.744Z',
      created_at_human: 'September 26, 2024 07:33',
      updated_at: '2024-09-26T07:33:56.841Z',
      gallery_id: 'R0phCW16tn',
      url: 'https://imgbox.com/ZeNbMgP7',
      original_url: 'https://images2.imgbox.com/b0/1f/ZeNbMgP7_o.jpg',
      thumbnail_url: 'https://thumbs2.imgbox.com/b0/1f/ZeNbMgP7_t.jpg',
      square_url: 'https://thumbs2.imgbox.com/b0/1f/ZeNbMgP7_b.jpg',
      selected: false,
      comments_enabled: 0,
      comments_count: 0
    }
  ]
}
```

There's `url`, `original_url`, `thumbnail_url`, and `square_url`. Just need to make sure you select correct properties.

**Comment by 0wx** [comment]
Whoops, didn't read the issue title, by default if you didnt specify the filename it will return `jpg`,
Simply put the file name like this example will fix the issue @zeteticl 
```js
const file = {
        filename: 'tes.png',
        url: 'https://picsum.photos/200'
    }
    
imgbox(file)
    .then(data => console.log(data))
```

**Comment by zeteticl** [comment]
The problem has been resolved! 
Thank you so much!

**Comment by zeteticl** [comment]
bur i got error with 
```
const file = {
        filename: 'tes.png',
        url: 'https://picsum.photos/200'
    }

```
so i use
```
const file = [{
        filename: 'tes.png',
        url: 'https://picsum.photos/200'
    }]

```

**Comment by 0wx** [comment]
yeah, this project haven't been updated for a while, will try to update when I could, thanks @zeteticl!
